// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsSBUkKaX1ktO7ZnO2STinqMRVTzFzkeU',
    appId: '1:673520634856:web:f08b86ed691036cbe6b25d',
    messagingSenderId: '673520634856',
    projectId: 'badhyata-6452a',
    authDomain: 'badhyata-6452a.firebaseapp.com',
    storageBucket: 'badhyata-6452a.firebasestorage.app',
    measurementId: 'G-SXZT02K2DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnTj5vb9fZs13qR1hA0GUkBStSPaVDwjw',
    appId: '1:673520634856:android:989069eebcfb9000e6b25d',
    messagingSenderId: '673520634856',
    projectId: 'badhyata-6452a',
    storageBucket: 'badhyata-6452a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgzQUEKHwR2LRIAwPvYyT_H3NxogSS_rA',
    appId: '1:673520634856:ios:db6586d399fa5b06e6b25d',
    messagingSenderId: '673520634856',
    projectId: 'badhyata-6452a',
    storageBucket: 'badhyata-6452a.firebasestorage.app',
    iosBundleId: 'com.example.jobshub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgzQUEKHwR2LRIAwPvYyT_H3NxogSS_rA',
    appId: '1:673520634856:ios:db6586d399fa5b06e6b25d',
    messagingSenderId: '673520634856',
    projectId: 'badhyata-6452a',
    storageBucket: 'badhyata-6452a.firebasestorage.app',
    iosBundleId: 'com.example.jobshub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsSBUkKaX1ktO7ZnO2STinqMRVTzFzkeU',
    appId: '1:673520634856:web:88d88531615d3894e6b25d',
    messagingSenderId: '673520634856',
    projectId: 'badhyata-6452a',
    authDomain: 'badhyata-6452a.firebaseapp.com',
    storageBucket: 'badhyata-6452a.firebasestorage.app',
    measurementId: 'G-D3XGWGNP18',
  );
}
